sudo: false
language: ruby
rvm:
- 2.2.2
addons:
  apt:
    packages:
      - python-dev
      - python-pip
      - python-lxml
      - libcairo2
      - libpango1.0-0
      - libgdk-pixbuf2.0-0
      - libffi-dev
      - shared-mime-info
      - python-virtualenv
script:
- virtualenv --system-site-packages ./venv
- . ./venv/bin/activate
- pip install WeasyPrint
- make
- make deploy
